apiVersion: v1
kind: ServiceAccount
metadata:
  name: seictl
  namespace: {{.Namespace}}
  labels:
    app.kubernetes.io/managed-by: flux
    tide.sei.io/cell-type: personal
    tide.sei.io/owner: {{.Alias}}
