name: GoReleaser

on:
  release:
    types: [ published ]
  workflow_dispatch:
  workflow_run:
    workflows: [Releaser]
    types: [completed]

permissions:
  contents: write

jobs:
  goreleaser:
    uses: sei-protocol/uci/.github/workflows/goreleaser-release.yml@monty/goreleaser-reusable-workflow
    with:
      go-version-file: go.mod
      checkout-latest-tag: ${{ github.event_name == 'workflow_run' }}
